export const typebill: { [key: number]: string } = {
  1: "icon-yinshi",
  2: "icon-fushilei",
  3: "icon-gongjiao",
  4: "icon-riyongpin",
  5: "icon-gouwuchekong",
  6: "icon-xuexi",
  7: "icon-yiliaofuwu",
  8: "icon-lvhang",
  9: "icon-friend",
  10: "icon-qita",
  11: "icon-nvxing",
  12: "icon-gongzihefang",
  13: "icon-licai",
  14: "icon-licai",
  15: "icon-tianmaojisutuikuan",
  16: "icon-qita",
};
